name: CI_CD_ACTION

on:
  pull_request:
    branches: [ main ]

env:
    DOCKER_REPOSITORY:  ${{ secrets.DOCKER_HUB_USERNAME }}/product-app # name of Docker Hub ID
    IMAGE_NAME: product-app
    IMAGE_TAG: v1 # $GITHUB_RUN_NUMBER

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore "./ProductApp.Api/ProductApp.Api.csproj"
      - name: Build
        run: dotnet build "./ProductApp.Api/ProductApp.Api.csproj" --no-restore
      - name: Test
        run: dotnet test "./ProductApp.Tests/ProductApp.Tests.csproj"
      # - name: Build Docker Image
      #   run: docker build ./ -t  ${{ secrets.DOCKER_HUB_USERNAME }}/product-app:v1
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #       username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #       password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      # - name: Push Image to Docker Hub
      #   run: docker push  ${{ secrets.DOCKER_HUB_USERNAME }}/product-app:v1
  
  setup:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Install Docker using Docker's official script
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
  
  build-publish-compose:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Build the docker-compose stack
        run: docker compose -f docker-compose.yml build
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push Image to Docker Hub
        run: docker push  ${{ secrets.DOCKER_HUB_USERNAME }}/product-app:v1

  cd-job-deploy:
    runs-on: ubuntu-latest
    needs: build-publish-compose
    steps:
      - uses: actions/checkout@v4
      - uses: helm/kind-action@v1.4.0
      - run: |
          kubectl cluster-info
          kubectl get nodes
      - name: Create the k8s-deployment for app
        run: |
            kubectl apply --validate=false -f ./app_deployment_manifest.yaml
            kubectl run  product-app --image=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/product-app:v1 --port=8080
            sleep 60
            kubectl get all
            kubectl port-forward product-app 8080:8080 &>/dev/null &
            sleep 20
            kubectl port-forward product-app 8081:8081 &>/dev/null &
      - run: |
          curl -i http://localhost:8080/
      # - name: Create the k8s-deployment for mongo
      #   run: kubectl apply --validate=false -f /.mongodb_deployment_manifest.yaml
