name: CI_ACTION

on:
  pull_request:
    branches: [ main ]

jobs:
  ci-job-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: product_app # name of Docker Hub ID
      IMAGE_NAME: webapp
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore "./ProductApp.Api/ProductApp.Api.csproj"
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test "./ProductApp.Tests.csproj" --no-build --verbosity normal
      
      - name: Build Docker Image
        run: docker build ./ProductApp.Api/ --file ./ProductApp.Api/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER --build-arg=token=ZGEzNTQ5Y2QyNjAx --no-cache
      - name: Login to Docker Hub
        run: |
              echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
      - name: Push Image to Docker Hub
        run: docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER    
